# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development CI

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: [self-hosted, dev]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        path: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: sudo docker compose up -d
    - name: Make prod envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DB_HOST: ${{ vars.PROD_DB_HOST }}
        envkey_DB_PORT: ${{ vars.PROD_DB_PORT }}
        envkey_DB_USER: ${{ vars.PROD_DB_USER }}
        envkey_DB_NAME: ${{ vars.PROD_DB_NAME }}
        envkey_NODE_ENV: prod
        envkey_DB_DROP_SCHEMA: 0
        envkey_JWT_EXPIRES_IN: ${{ vars.PROD_JWT_EXPIRES_IN }}
        envkey_SECRET_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        envkey_SECRET_JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
        file_name: prod.env
        fail_on_empty: false
        sort_keys: false
    - name: Make dev envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DB_HOST: ${{ vars.DEV_DB_HOST }}
        envkey_DB_PORT: ${{ vars.DEV_DB_PORT }}
        envkey_DB_USER: ${{ vars.DEV_DB_USER }}
        envkey_DB_NAME: ${{ vars.DEV_DB_NAME }}
        envkey_NODE_ENV: dev
        envkey_DB_DROP_SCHEMA: 0
        envkey_JWT_EXPIRES_IN: ${{ vars.DEV_JWT_EXPIRES_IN }}
        envkey_SECRET_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        envkey_SECRET_JWT_SECRET: ${{ secrets.DEV_JWT_SECRET }}
        file_name: dev.env
        fail_on_empty: false
        sort_keys: false
    - run: npm run build --if-present
    - run: pm2 restart ./dist/main.js
